name: build.yml
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          chmod +x ./gradlew
          ./gradlew build
      - run: |
          gh release create ${{ github.ref }} \
          --title "${{ github.ref }}" \
          --files build/libs/*.jar